version: "3.8"

services:
    db:
        image: postgres:15-alpine
        container_name: cengstaj_postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: cengstajprototippostgres
            POSTGRES_DB: cengstaj_db
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: cengstaj_pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@cankaya.edu.tr
            PGADMIN_DEFAULT_PASSWORD: adminpassword
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    postgres_data:
